site_name: Bioinformatics 

# configurations: dont change unless you know what you are doing!
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: octicons/chevron-right-24
  include_search_page: true
  search_index_only: true
  language: en
  features:
    - navigation.tabs
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
  palette: 
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate 
      primary: red
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

copyright: ©2021

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rki-bir
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/martinhoelzer
    - icon: fontawesome/brands/google
      link: https://scholar.google.com/citations?user=DMZ7Hc8AAAAJ&hl=en
#    - icon: fontawesome/brands/researchgate
#      link: https://www.researchgate.net/profile/Christian_Brandt5
#    - icon: fontawesome/brands/linkedin
#      link: https://de.linkedin.com/in/christian-b-a2b05018a

plugins:
  - search
  - bibtex:
      bib_file: "refs.bib"
      cite_style: "pandoc"

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - footnotes 
#  - mdx_bibtex

# Navigation
## USE SPACE not TAB
nav:
- Home: index.md
#- People:
#        - Team: team.md
#        - Martin Hölzer, PhD: team/martin.md
#        - Hugues Richard, PhD: team/hugues.md
#        - Matt Huska, PhD: team/matt.md
#        - Alumni: team/alumni.md
- Publications: publications.md
- Tools: tools.md
#- Collaborations: collaborations.md
#- Projects: projects.md
