name: ci 
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      # rubyscholar citation stuff
      - run: conda install -y -c conda-forge ruby
      - run: sudo gem install bundler:1.11.2
      - run: bundle install --gemfile rubyscholar/Gemfile
      - run: cp rubyscholar/config.yaml .
      - run: bundle exec --gemfile rubyscholar/Gemfile rubyscholar
      # done with rubyscholar citation stuff
      - run: pip install mkdocs-material mkdocs-bibtex 
      - run: mkdocs gh-deploy --force
